version: "3"

services:

  runtime-setup:
    image: swift-nio:18.04-4.2
    build:
      args:
        ubuntu_version : "18.04"
        swift_version : "4.2"
        skip_ruby_from_ppa : "true"

  unit-tests:
    image: swift-nio:18.04-4.2

  integration-tests:
    image: swift-nio:18.04-4.2
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=36750
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=603000
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4550
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2050
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99050
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150

  test:
    image: swift-nio:18.04-4.2
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=36750
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=603000
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4550
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2050
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99050
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150

  echo:
    image: swift-nio:18.04-4.2

  http:
    image: swift-nio:18.04-4.2
