version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: swift build
      - run: swift test
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      # - macos
      - linux
