version: 2

jobs:
  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  linux-release:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release
  linux-fluent:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - run:
          name: Clone Fluent SQLite
          command: git clone -b master https://github.com/vapor/fluent-sqlite.git
          working_directory: ~/
      - run:
          name: Switch Fluent SQLite to this SQLite revision
          command: swift package edit SQLite --revision $CIRCLE_SHA1
          working_directory: ~/fluent-sqlite
      - run:
          name: Run Fluent SQLite unit tests
          command: swift test
          working_directory: ~/fluent-sqlite
workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-fluent
      - linux-release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
